using Microsoft.Extensions.DependencyInjection;
using Finova.Countries.Europe.Albania.Validators;
using Finova.Countries.Europe.Andorra.Validators;
using Finova.Countries.Europe.Austria.Validators;
using Finova.Countries.Europe.Azerbaijan.Validators;
using Finova.Countries.Europe.Belarus.Validators;
using Finova.Countries.Europe.Belgium.Validators;
using Finova.Countries.Europe.BosniaAndHerzegovina.Validators;
using Finova.Countries.Europe.Bulgaria.Validators;
using Finova.Countries.Europe.Croatia.Validators;
using Finova.Countries.Europe.Cyprus.Validators;
using Finova.Countries.Europe.CzechRepublic.Validators;
using Finova.Countries.Europe.Denmark.Validators;
using Finova.Countries.Europe.Estonia.Validators;
using Finova.Countries.Europe.FaroeIslands.Validators;
using Finova.Countries.Europe.Finland.Validators;
using Finova.Countries.Europe.France.Validators;
using Finova.Countries.Europe.Georgia.Validators;
using Finova.Countries.Europe.Germany.Validators;
using Finova.Countries.Europe.Gibraltar.Validators;
using Finova.Countries.Europe.Greece.Validators;
using Finova.Countries.Europe.Greenland.Validators;
using Finova.Countries.Europe.Hungary.Validators;
using Finova.Countries.Europe.Iceland.Validators;
using Finova.Countries.Europe.Ireland.Validators;
using Finova.Countries.Europe.Italy.Validators;
using Finova.Countries.Europe.Kosovo.Validators;
using Finova.Countries.Europe.Latvia.Validators;
using Finova.Countries.Europe.Liechtenstein.Validators;
using Finova.Countries.Europe.Lithuania.Validators;
using Finova.Countries.Europe.Luxembourg.Validators;
using Finova.Countries.Europe.Malta.Validators;
using Finova.Countries.Europe.Moldova.Validators;
using Finova.Countries.Europe.Monaco.Validators;
using Finova.Countries.Europe.Montenegro.Validators;
using Finova.Countries.Europe.Netherlands.Validators;
using Finova.Countries.Europe.NorthMacedonia.Validators;
using Finova.Countries.Europe.Norway.Validators;
using Finova.Countries.Europe.Poland.Validators;
using Finova.Countries.Europe.Portugal.Validators;
using Finova.Countries.Europe.Romania.Validators;
using Finova.Countries.Europe.SanMarino.Validators;
using Finova.Countries.Europe.Serbia.Validators;
using Finova.Countries.Europe.Slovakia.Validators;
using Finova.Countries.Europe.Slovenia.Validators;
using Finova.Countries.Europe.Spain.Validators;
using Finova.Countries.Europe.Sweden.Validators;
using Finova.Countries.Europe.Switzerland.Validators;
using Finova.Countries.Europe.Turkey.Validators;
using Finova.Countries.Europe.Ukraine.Validators;
using Finova.Countries.Europe.UnitedKingdom.Validators;
using Finova.Countries.Europe.Vatican.Validators;

namespace Finova.Extensions.DependencyInjection;

public static class IbanValidatorsExtensions
{
    public static IServiceCollection AddIbanValidators(this IServiceCollection services)
    {
        services.AddSingleton<AlbaniaIbanValidator>();
        services.AddSingleton<AndorraIbanValidator>();
        services.AddSingleton<AustriaIbanValidator>();
        services.AddSingleton<AzerbaijanIbanValidator>();
        services.AddSingleton<BelarusIbanValidator>();
        services.AddSingleton<BelgiumIbanValidator>();
        services.AddSingleton<BosniaAndHerzegovinaIbanValidator>();
        services.AddSingleton<BulgariaIbanValidator>();
        services.AddSingleton<CroatiaIbanValidator>();
        services.AddSingleton<CyprusIbanValidator>();
        services.AddSingleton<CzechRepublicIbanValidator>();
        services.AddSingleton<DenmarkIbanValidator>();
        services.AddSingleton<EstoniaIbanValidator>();
        services.AddSingleton<FaroeIslandsIbanValidator>();
        services.AddSingleton<FinlandIbanValidator>();
        services.AddSingleton<FranceIbanValidator>();
        services.AddSingleton<GeorgiaIbanValidator>();
        services.AddSingleton<GermanyIbanValidator>();
        services.AddSingleton<GibraltarIbanValidator>();
        services.AddSingleton<GreeceIbanValidator>();
        services.AddSingleton<GreenlandIbanValidator>();
        services.AddSingleton<HungaryIbanValidator>();
        services.AddSingleton<IcelandIbanValidator>();
        services.AddSingleton<IrelandIbanValidator>();
        services.AddSingleton<ItalyIbanValidator>();
        services.AddSingleton<KosovoIbanValidator>();
        services.AddSingleton<LatviaIbanValidator>();
        services.AddSingleton<LiechtensteinIbanValidator>();
        services.AddSingleton<LithuaniaIbanValidator>();
        services.AddSingleton<LuxembourgIbanValidator>();
        services.AddSingleton<MaltaIbanValidator>();
        services.AddSingleton<MoldovaIbanValidator>();
        services.AddSingleton<MonacoIbanValidator>();
        services.AddSingleton<MontenegroIbanValidator>();
        services.AddSingleton<NetherlandsIbanValidator>();
        services.AddSingleton<NorthMacedoniaIbanValidator>();
        services.AddSingleton<NorwayIbanValidator>();
        services.AddSingleton<PolandIbanValidator>();
        services.AddSingleton<PortugalIbanValidator>();
        services.AddSingleton<RomaniaIbanValidator>();
        services.AddSingleton<SanMarinoIbanValidator>();
        services.AddSingleton<SerbiaIbanValidator>();
        services.AddSingleton<SlovakiaIbanValidator>();
        services.AddSingleton<SloveniaIbanValidator>();
        services.AddSingleton<SpainIbanValidator>();
        services.AddSingleton<SwedenIbanValidator>();
        services.AddSingleton<SwitzerlandIbanValidator>();
        services.AddSingleton<TurkeyIbanValidator>();
        services.AddSingleton<UkraineIbanValidator>();
        services.AddSingleton<UnitedKingdomIbanValidator>();
        services.AddSingleton<VaticanIbanValidator>();

        return services;
    }
}
